services:
  alphatensor_www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alphatensor_www
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "3000:3000"
