version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-app:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    # Uncomment the following lines for development
    # volumes:
    #   - .:/app:delegated
    #   - /app/node_modules
    # command: npm run dev